### PR TITLE
MNT: rerender

### LINKED ISSUE #15: @conda-forge-admin, please re-render
@conda-forge-admin, please re-render.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #15.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #15

### CODE REVIEW

**Comment by dgasmith** [comment]
@jakirkham Looks like `noarch` was removed. Is this expected?

**Comment by jakirkham** [comment]
I don't see [`noarch` in the `meta.yaml` on `master`]( https://github.com/conda-forge/opt_einsum-feedstock/blob/31919b8e7ba5b8eb0aaed59f490281cdb4881b43/recipe/meta.yaml#L14-L16 ). Should it be added?

**Comment by jakirkham** [comment]
Actually all CIs were enabled before too, which would not be true if it were `noarch`. What am I missing?

**Comment by dgasmith** [comment]
I see, I haven't touched this repo in awhile. It should be moved to `noarch` at some point as the individual builds are not required. Apologies for this assumption, this PR is good to go and I can rebuild as noarch later.

**Comment by jakirkham** [comment]
No worries. Sounds reasonable. Not at all. Just wanted to make sure I wasn't missing something.

**Pull request merged**
